<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Mutation</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
    <PackageReference Include="MSBuild.StructuredLogger" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../../typemodeling-dotnet/src/TypeModeling/TypeModeling.csproj" />
    <ProjectReference Include="../../../typemodeling-dotnet/src/TypeModeling.Analyzers/TypeModeling.Analyzers.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false"
                      SkipGetTargetFrameworkProperties="true" />
  </ItemGroup>
</Project>
