<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="xunit.runner.utility" />
    <PackageReference Include="Microsoft.TestPlatform.ObjectModel" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="../Mutation/protocol/*.cs" LinkBase="protocol" />
  </ItemGroup>
</Project>
